### ISSUE TITLE
End stream after $ element have been removed

### ISSUE THREAD

**Issue by gyzerok** [baconjs/bacon.js#498]
Wouldn't it be nice to end stream obtained from $el.asEventStream method after $el have been removed?

Not sure I'm undersood your code right but check this:
```coffeescript
Bacon.$.asEventStream = (eventName, selector, eventTransformer) ->
[eventTransformer, selector] = [selector, undefined] if isFunction(selector)
    withDescription(@selector or this, "asEventStream", eventName, Bacon.fromBinder (handler) =>
        @on('remove', -> handler new Bacon.End)
        @on(eventName, selector, handler)
        => @off(eventName, selector, handler)
    , eventTransformer)
```

**Comment by AgentME** [comment]
I use Bacon.fromEventTarget (not exactly Bacon.$.asEventStream, but pretty close) on elements that are removed from the DOM and sometimes re-added elsewhere. DOM nodes don't forget their event listeners when they're removed from the DOM, and can event continue to emit events while not being attached, so I would have been very surprised and bothered if Bacon had turned a blind eye to those nodes.

**Comment by raimohanska** [comment]
I guess we're done here, are we? Suggesting Close.

**Comment by djskinner** [comment]
The discussion above is the perfect context for my question so I hope you don't mind me continuing this thread rather than opening a new issue.

I am just wondering if there is any problems with calling `fromEvent` multiple times on a DOM element for the same `target` and `eventName`? In my situation React may re-render without the element and when it renders it back in again I just call `fromEvent` again. I'm not sure if React reuses the same DOM element of not and I'm hoping I don't have to care.

To be honest I like @mkaemmerer 's explicit approach of `$foo.asEventStream('click').takeUntil($foo.asEventStream('remove'))` rather than my current approach of potentially calling `fromEvent` multiple times and it might be worth adding this sweet slice of Bacon goodness to the docs for newbies like me.

**Comment by AgentME** [comment]
If you call fromEvent on a node multiple times without ever unsubscribing, then you'll have a memory leak as more event listeners get bound to the element.

If you're using Bacon to listen to events from a node created by React, I think you're probably using React wrongly. If you really must go that way, then create a bus in componentDidMount, use `Bacon.fromEvent(this.refs.yourDomNode).takeUntil(yourBus)...` once in componentDidMount, and then have the bus emit something in componentWillUnmount.

**Comment by djskinner** [comment]
Could you elaborate on how  might be misusing React? Creating an event stream of button clicks seemed like a clean solution to me in a Flux architecture.

**Comment by johannhof** [comment]
@djskinner Ideally you would have the components listen to their own `onClick` and then emitting some sort of event in an emitter you built yourself. The streams then listen to that event.

This way you keep view implementation knowledge out of your streams, don't have to reattach a listener whenever React renders and just leave it to React to attach and disattach the `onClick` handler that calls your emitter function in a clean and performant way.

**Comment by djskinner** [comment]
Yeah when put like that it makes a lot of sense. Thanks @johannhof .
