### ISSUE TITLE
Can't raise `Bacon.Error` within a `map`

### ISSUE THREAD

**Issue by eguneys** [baconjs/bacon.js#524]
I can't raise a `Bacon.Error` within a map:

    var mapError = Bacon.fromArray([1,2,3]).map(function(v) {
      if (v == 2) {
        return new Bacon.Error("not 2");
      }
      return v;
    });
    
    mapError.onValue(function(v) {
      console.log(v);
    });
    // output: 
    // 1
    // <error> not 2
    // 3

I expect `2` to not appear for `onValue` but it does appear as  `<error> 2`.

**Comment by bleadof** [comment]
You can solve this by using flatMap and producing a new stream with Bacon.once.
```javascript
.flatMap(function(value) {
  if(value === 2)  return Bacon.once(new Bacon.Error('yup, two'));
  return Bacon.once(value);
})
```
I didn't run the code but wrote it on top of my head so, i might be a bit wrong, but you get the idea. :-)

**Comment by philipnilsson** [comment]
This is explicitly mentioned in the documentation for Error so I'm closing this. @eguneys, if you want some intuition on why flatMap is needed, consider that it's possible to have an event stream containing Bacon events, rather than values, and it's possible to implement e.g. functions

`Bacon.reify :: Bacon.EventStream<Int> -> Bacon.EventStream<Bacon.Event<Int>>`
`Bacon.interpret :: Bacon.EventStream<Bacon.Event<Int>> -> Bacon.EventStream<Int>`

Using a mix of C#/Haskell type signatures here, hope you can understand it. Basically there are the concepts of a "stream of ints", and i'ts not the same as a "stream of events, containing ints".

Not sure if these combinators have been added to Bacon, but in RxJava they are implemented as combinators `materialize` / `dematerialize`, which you can find documentation for at http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable

The short answer is that of @bleadof, just use `flatMap` instead of `map`.
