### ISSUE TITLE
Returning Bacon.noMore from .subscribe doesn't reflect in source sink's return value until next event loop run

### ISSUE THREAD

**Issue by AgentME** [baconjs/bacon.js#527]
Here I have a stream source that emits events synchronously until it `sink` returns with `Bacon.noMore`. However, returning Bacon.noMore from the subscribe callback fails to cause sink in the source to return Bacon.noMore. It's not until .take(10) gets its 10 events that the source's sink returns correctly.

```javascript
var Bacon = require('baconjs');

var i = 0;
Bacon.fromBinder(function(sink) {
  while (true) {
    var response = sink(i++);
    console.log('source got', response);
    if (response === Bacon.noMore)
      break;
  }
}).take(10).subscribe(function(event) {
  console.log('subscribe got', event);
  return Bacon.noMore;
});
```

If you remove the `.take(10)` part in the middle, then the node process never exits.

**Comment by AgentME** [comment]
Actually, it doesn't seem like the synchronicity is the main part of the problem. This code only emits events asynchronously.

```javascript
var Bacon = require('baconjs');

var i = 0;
Bacon.fromBinder(function(sink) {
  var timer = setInterval(function() {
    console.log('about to emit', ++i);
    var response = sink(i);
    console.log('source got', response);
    if (response === Bacon.noMore)
      clearInterval(timer);
  }, 0);
}).subscribe(function(event) {
  console.log('subscribe got', event);
  return Bacon.noMore;
});
```

Here's the output:
```
about to emit 1
subscribe got 1
source got [ '<more>' ]
about to emit 2
source got [ '<no-more>' ]
```

The fact that the subscribe callback unsubscribed isn't communicated to the source until the next event. (Or event loop run, which explains the first post's code's behavior.)

**Comment by raimohanska** [comment]
You're correct in that the `noMore` value is not passed as-is. However, the returned unsubscribe-function is called and the system works correctly as a whole.

The reason for not passing `noMore` is because it's impossible due to the fact that "external" subscribers get called only after the whole event transaction is done with. This shouldn't be a problem because the unsubscribe-function will get called anyway. Also, using combinators like `take` is recommended instead of returning `noMore` from your subscriber.
