### ISSUE TITLE
Cannot use EventStreams in two different modules

### ISSUE THREAD

**Issue by tzanko-matev** [baconjs/bacon.js#578]
When using baconjs in a Node.js program it can happen that the baconjs module is loaded twice. Consider the following example.

module1.js:

``` coffeescript
bacon = require 'baconjs'
exports.Observable = bacon.Observable
```

module2.js:

``` coffeescript
bacon = require 'baconjs'
exports.Observable = bacon.Observable
```

main.js:

``` coffeescript
module1 = require 'module1'
module2 = require 'module2'
console.log module1.Observable == module2.Observable
```

If the modules _module1_ and _module2_ have different node_modules directories, then the program will print 'false'. This becomes an issue because bacon checks if an object is an Observable with `object instanceof Observable`. So when I apply flatMap on a module1.Observable using as a parameter a function which returns a module2.Observable, flatMap thinks that the returned value is not an Observable and it gets wrapped.

**Comment by lautis** [comment]
Have you tried [npm dedupe](https://docs.npmjs.com/cli/dedupe) or [peer dependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/)? Even if the observables returned by the other module would be accepted/not wrapped, Bacon has loads of internal state that isn't shared between different Bacon (library) instances. This is similar issue as [using Bacon.js in cross-frame contexts](https://github.com/baconjs/bacon.js/wiki/FAQ#what-if-i-have-multiple-frames-in-my-application).

**Comment by AgentME** [comment]
Relying on npm dedupe for correctness rather than just efficiency sounds like it will lead to pain because you'll have to instruct your users to always use it. And the users of applications that use libraries that use your libraries, etc.

Peer dependencies sounds like the correct solution if you have a module that can only be used by a module that must be already using Bacon itself. However, if your module only has optional compatibility with Bacon and you don't want to force users of your module to also install Bacon themselves, then (my module) [bacon-cast](https://www.npmjs.com/package/bacon-cast) is probably the right solution instead of a peer dependency.

**Comment by tzanko-matev** [comment]
Thanks for the advice, bacon-cast seems to be the right solution for me. I was surprised that this functionality is not already part of bacon itself. If it cannot be fixed then I think that the problem should at least be mentioned in the docs to avoid any confusion.

**Comment by raimohanska** [comment]
This is duplicate to #296

**Comment by raimohanska** [comment]
Peer dependencies are the go-to solution here
