### ISSUE TITLE
Scan is inconsistent with logging

### ISSUE THREAD

**Issue by arnfredj** [baconjs/bacon.js#605]
eventStream.scan seems inconsistent when eventStreams and properties are logged.

Here are some examples:

```javascript
// Normal case
var a = Bacon.once({ "a" : 1 });
var b = Bacon.once({ "b" : 2 });
var changes = Bacon.mergeAll(a,b)
var r = changes.scan({}, _.merge).log("r")
	> "r" Object { a: 1 }
	> "r" Object { a: 1 }
	> "r" Object { a: 1, b: 2 }
	> "r" "<end>"

// Now adding a log to changes
var a = Bacon.once({ "a" : 1 });
var b = Bacon.once({ "b" : 2 });
var changes = Bacon.mergeAll(a,b)
var r = changes.log("changes").(scan({}, _.merge).log("r")
	> "changes" Object { a: 1 }
	> "changes" Object { b: 2 }
	> "changes" "<end>"
	> "r" Object {  }
	> "r" "<end>"

// With changes as a property
var a = Bacon.once({ "a" : 1 });
var b = Bacon.once({ "b" : 2 });
var changes = Bacon.mergeAll(a,b).toProperty();
var r = changes.log("changes").(scan({}, _.merge).log("r")
	> "changes" Object { a: 1 }
	> "changes" Object { b: 2 }
	> "changes" "<end>"
	> "r" Object { b: 2 }
	> "r" "<end>"
```

For at least the latter case using properties, the expected outcome would be that changes would also fire an event containing `Object { a: 1, b: 2}`. Is that correct?

**Comment by raimohanska** [comment]
Hi, one thing that causes confusion here is that `_.merge` from lodash mutates its arguments. It's strongly recommended that you only use pure functions in scan (as well as other Bacon.js methods). This explains why in "normal case" your first object is `{a:1}` instead of `{}`.

In your second case, when adding a subscriber to `changes`, the first subscriber drains the `Bacon.once` sources and there are no more events left for later subscribers.

In your last case, `changes` is a Property and thus retains its latest value. So after you've drained the sources using the subscriber on `changes`, you're left with its last value `{b:2}` that it repeats for `r` and thus is the sole output of `r`.

**Comment by raimohanska** [comment]
So once a again a case where synchronous event sources (such as Bacon.once) fooled the user. This time with mutating functions as their sidekick. Yet, everything works as expected here.

**Comment by arnfredj** [comment]
That makes perfect sense. Thanks a lot for your response. I hope it might help someone else who is having the same problem.
