### ISSUE TITLE
EventStreams firing simultaniously doesn't combine well with properties

### ISSUE THREAD

**Issue by arnfred** [baconjs/bacon.js#627]
I can't seem to make Bacon play well with simultaneous events:
```javascript
var a = Bacon.fromArray([1,2,3]);
var b = Bacon.constant("b")
Bacon.combineTemplate({a: a, b: b}).log()
```
Returns
```javascript
Object { a: 3, b: "b" }
```
Where as I would expect it to return:
```javascript
Object { a: 1, b: "b" }
Object { a: 2, b: "b" }
Object { a: 3, b: "b" }
```
The same goes for `combine`, `combineAsArray` and any other way I've tried to combine the two event streams. Is there any way I can get the result I'm expecting?

**Comment by jackjennings** [comment]
The issue is using `fromArray`, which will send all of it's events to the first subscriber immediately. By the time `log` subscribes to the `combineTemplate` stream, the property already is set to the final value. Try using `sequentially` instead. `fromArray` is mostly useful when using `flatMap` and cousins.

**Comment by philipnilsson** [comment]
The issue is as @jackjennings said about event sources that publish their events synchronously, which introduces some non-commutativity where you might not expect it. For instance, reversing the order of elements, to `Bacon.combineTemplate({b: b, a: a}).log();` will also do the job here, but switching to `sequentially` is generally safer.

**Comment by arnfred** [comment]
The reason I ask is the following scenario:

Event stream `a` and event stream `b` are generally independent but both fire when event stream `c` fires. This means that for some events, `a` and `b` are synchronious, but for most they aren't.

From `a` and `b` I'm defining `d = Bacon.when([a], doSomething, [b], doSomethingElse)` but only `doSomething` will fire when both update synchroniously.

I gave the slightly simpler example above because it exhibited the same behavior, but in my actual use case I can't quite switch to `sequentially`.

Is there any way I can work around the fact that `a` and `b` happen to be synchronous on certain events?

**Comment by raimohanska** [comment]
Combined properties only fire once for several simultaneous triggers and that's by design. It's [Atomic updates](https://github.com/baconjs/bacon.js/#atomic-updates) in action.

If you want your result stream to fire every time `d` or `c` fires, you can say

    e = d.combine(c, someFunction).sampledBy(d.merge(c))

So, simultaneous events are not a problem.

But, once again, synchronously responding streams, like `Bacon.fromArray`, do cause confusion. Like in your original problem description where you got only one output instead of the expected 3 outputs. That's not because of atomic updates, but instead it happens because `a` responds synchronously and emits all the values `[1,2,3]` before the `b` has output anything (just like @jackjennings  pointed out indeed). The result is that the values don't get combined until both inputs have emitted at least one value. If you change your last line to `Bacon.combineTemplate({a: a, b: b}).log()`, you'll get more outputs. This is why I'd very much like to fix #367. As a workaround for problems related to `Bacon.fromArray` you can always use `Bacon.sequentially` just like @philipnilsson suggested above.

**Comment by philipnilsson** [comment]
I closed this as a bug since it seems everything is indeed working as intended, both `fromArray` and "atomic updates". You might have a question about modelling, in which case the best action might be to open a StackOverflow question if you have an account, and link it here.

In this case any help we can give you becomes more easily googlable than closed github issues, so we greatly prefer this.

**Comment by arnfred** [comment]
Thanks a lot for all your answers. I appreciate your quick and thorough response.

I'll use stackoverflow for clarifications in the future.
